### ISSUE TITLE
OpenSearchSource doesn't have a configurable poll interval

### ISSUE THREAD

**Issue by rymach** [codice/ddf#4284]
### Description

Improvement: OpenSearchSource doesn't have a configurable poll interval

We have a server admin that would like us to stop polling him every minute. Other sources allow you to change the poll interval, but not this one.

Issue is not a bug. 

### Steps to Reproduce (if issue is bug)

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior:
[What you expect to happen]

#### Actual behavior:
[What actually happens]

#### Reproduces how often:
[What percentage of the time does it reproduce?]

### Version
[Application version]

### Additional Information
Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by vinamartin** [comment]
Please use the issue template to describe why this change is needed. https://github.com/codice/ddf/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by rymach** [comment]
Updated, however the issue is not a bug so I think many of the fields do not apply.

**Comment by vinamartin** [comment]
Okay but why does this need to be configurable? 
What's the background on this ticket?

**Comment by coyotesqrl** [comment]
@rymach If it's not a bug, then presumably it's an improvement or new feature (I'm speaking in general; this is clearly a suggested improvement on existing functionality).

Our current Issue template is still pretty basic and can definitely be improved to better support reporting of bugs, feature requests, dependency upgrades, enhancements, etc. and as a contributor to DDF we welcome your suggestions or PRs to make those process improvements, both during this pilot program and beyond. It's agility- and transparency-turtles all the way down.

But even without making template changes, it's certainly possible to edit the entire contents of the Issue report - as you surmised - to better fit the needs of the issue you are currently reporting. In this case, a description of the _why_ of the improvement would be helpful. Adding yet another knob or dial to DDF - if that's the form this enhancement would take - makes it that much more complicated to document, install, and administer; we need to weigh the flexibility and complexity of all those knobs and dials as compared to a less flexible, more opinionated system.

In a case like this one, especially, the issue report is the best place to document your assumptions, problems, and needs - the _why_ of the change - such that it can be reviewed and discussed lest a solution be started before a consensus on the change request can even be reached. Without sufficient details, that discussion can't even begin.

**Comment by rymach** [comment]
Sorry about the lack of detail on the original issue.

We have a server admin that would like us to stop polling him every minute. Other sources allow you to change the poll interval, but not this one.

**Comment by coyotesqrl** [comment]
@rymach That's great explanatory information. Knowing that there is a use case for this change that makes sense and that it will make this source more alike other sources than less alike will help give the community confidence it is a good enhancement. That's the sort of stuff we're all hoping to see in our issue reports.

I'm sure you know how..._sparse_...some of our Jira tickets have been traditionally and one of the things we're hoping to see during this pilot is if we can do a better job of being more transparent, more communicative, and just plain better.

**Comment by rymach** [comment]
👍
