### ISSUE TITLE
Issue Template improvements

### ISSUE THREAD

**Issue by Kjames5269** [codice/ddf#4286]
### Description
Improving the quality of the issue templates by making them easier to use, and more informative for both developers and committers of this repository.

### Additional Information

While we're still in the pilot program using git for our ticket tracking, this ticket will remain open.

#### If you're putting up a PR for this issue remove `fixes` before this ticket number.

**Comment by coyotesqrl** [comment]
Reopening for the duration of the pilot as a single issue to coordinate Issue Template improvements.

**Comment by coyotesqrl** [comment]
@peterhuffer points us to these templates that he's using on a project right now - https://github.com/connexta/replication/tree/master/.github/ISSUE_TEMPLATE

That's not a bad set.

**Comment by Kjames5269** [comment]
I agree, I do like how they incorporate platforms within their bug tickets as well, but I feel a lot of what they have should be in comments 🙂

**Comment by peterhuffer** [comment]
The task.md in replication is sort of a catch all for anything that is not a bug or feature request. The plan was that a task in combination with GitHub labels could be used to filter/search those tasks more efficiently.

**Comment by coyotesqrl** [comment]
From @michaelmenousek:

> bugs should be written as a negative, from the users point of view, with workaround
> 
> `Usernames with apostrophes cannot authenticate, forcing administrators to rename users to allow access`
> 
> new feature ideas should be written as positive, ideally starting with a component name or verb
> `Support retina scans as authentication credential`
> 
> Stories are even better and should follow the structure: `As a < type of user >, I want < some goal > so that < some reason >.`
> https://www.mountaingoatsoftware.com/agile/user-stories
> `As a user, I want to authenticate with my retina, so that I don't have to remember a password and nobody else can get into my account`
> 
> tech debt tickets could really be anything
> `Authentication subsystem only allows text credentials` or `refactor authentication subsystem to allow pluggable credential types`

And a link to some good examples: https://www.mountaingoatsoftware.com/agile/user-stories
