### ISSUE TITLE
Refactor Location Radio Buttons to Dropdown

### ISSUE THREAD

**Issue by Schachte** [codice/ddf#4297]
### Description

Currently, as we extend the location component to support more items, BBOX, polygon etc. As the number of items in this section grows, the UI starts to look strange. 

Given that this plugin is extensible and used downstream, the numbers of items has already started to grow and makes for a poor user experience. 

This **UI enhancement** seeks to remediate this problem by placing everything in a scrollable dropdown. 

**Current** 
<img width="613" alt="screen shot 2019-01-31 at 8 58 02 am" src="https://user-images.githubusercontent.com/7055226/52066716-579ed700-2536-11e9-8e3d-e1496d18d88e.png">

**Inevitable Issues (Mockup)** 
<img width="1905" alt="screen shot 2019-01-31 at 8 59 15 am" src="https://user-images.githubusercontent.com/7055226/52066804-8321c180-2536-11e9-9fa1-20f83ccd6d5b.png">

**Proposed Change**
<img width="507" alt="screen shot 2019-01-31 at 8 42 11 am" src="https://user-images.githubusercontent.com/7055226/52065662-3c32cc80-2534-11e9-8391-6babcc1844d1.png">

### Steps to Reproduce (if issue is bug)

1. Search
2. Go to location and select `Somewhere Specific`
3. See Radio buttons to be replaced with above image

**Comment by coyotesqrl** [comment]
Could you elaborate on the description of this change? I can't tell if it's a bug or an enhancement and don't know what the expected and desired behavior are. 

An enhancement maybe? There are currently radio buttons being used that should be converted to a dropdown? Is that it? Could you provide a screenshot of how it looks now and an explanation of the reasoning to change it and how that change will be an improvement?

**Comment by Schachte** [comment]
@coyotesqrl I've updated the description.

**Comment by coyotesqrl** [comment]
That's perfect, @Schachte. Thanks! 👍
