### ISSUE TITLE
Add support for preQueryPlugin to be async

### ISSUE THREAD

**Issue by willwill96** [codice/ddf#4301]
### Description

Add support for the frontend preQueryPlugin in the `Query` model to be an async function. 
This will give more flexibility to what the plugin can do. For example, this will allow the plugin to fetch data before adding the data/payload to the search request.

This will *not* affect the PreQueryPlugin in the catalog framework

Special care should be taken to ensure that functions that use the return value of `startSearch` in the Query Model handle the returned promise gracefully

#### Expected behavior:

Searches to still operate the same from the user perspective
### Version

2.14.0
### Additional Information
Any additional information, or data that might be useful to know about

**Comment by coyotesqrl** [comment]
Is this a proposed change to make all pre-query plugins run asynchronously or to be able to in some way indicate that a specific implementation of the service should be run async?

Does this imply that the framework can fire off N pre-query plugins to run in parallel and then wait before moving onto the next processing step? Would there be a timeout for these async operations? Would it be a failure condition if any of the async plugins didn't complete before timing out or would that be a logged warning and the query process would continue?

Are there any concerns about async plugins stepping on each other during parallel processing? Would there be any mechanism in place to protect shared resources and state?

**Comment by coyotesqrl** [comment]
I see from quickly glancing at the PR that's gone up against this issue that it is UI related and does not impact `PreQueryPlugin`s in the catalog. As that wasn't clear, I think this issue needs a bit more meat in the description to clarify the use cases.

Also, some of my earlier questions - regarding shared resources/state, timeouts, and failures of individual plugins - still seem relevant.

**Comment by willwill96** [comment]
Updated the description 😄 
As for shared resources/state, etc., the main concern is making sure that the new return value (was an array but now is a promise) is handled gracefully. 
Parallel plugins should not be an issue as the `preQueryPlugin` in the frontend is a single function, and if you start a new query, the old one will be deleted, meaning there will never be multiple operating simultaneously. Any implementation that operates differently is up to downstream projects to work out the kinks.
