### ISSUE TITLE
Rename "Catalog UI Search" to "Catalog Search UI" in configurations

### ISSUE THREAD

**Issue by emmberk** [codice/ddf#4303]
### Description

I propose rewording "Catalog UI Search" to "Catalog Search UI" the `Search UI` configurations:
![image](https://user-images.githubusercontent.com/8041246/52084209-c2640880-255e-11e9-914c-981baeb38011.png)

There are currently 2 different Catalog search UIs included in DDF: Intrigue and Simple Search UI. There isn't only one "Search UI", and I don't think there will be other types of UIs for Catalog than Search UIs. I think this rename will make this fact clearer and be obvious that the configurations affect Intrigue, not "the only search UI".

#### Expected behavior:

- The Admin Console and the Documentation are updated to make clear that there are 2 search UIs: Simple Search UI and Catalog Search UI (a.k.a Intrigue).
- Intrigue configurations should be designated to indicate that they affect Intrigue, not all Search UIs/the Search UI.

### Version
2.14.0

### Additional Information
This ticket was spawned from https://github.com/codice/ddf/issues/4291.

**Comment by emmberk** [comment]
I'm working on this.

**Comment by emmberk** [comment]
I am not working this ticket.

**Comment by shaundmorris** [comment]
Closing since this hasn't been worked in a year and the Catalog Search UI was moved to ddf-ui
