### ISSUE TITLE
As an administrator, I'd like finer control on who can see warnings and errors

### ISSUE THREAD

**Issue by austinsteffes** [codice/ddf#4321]
### Description

After a merge, merge lost the ability for admins to say "I want no users to see my machine's errors and/or warnings, but I want my users to see errors/warnings from other machines if the other machine wants to show me errors/warnings".

### Version

Master/2.13.x

**Comment by emmberk** [comment]
Reopened because a new PR was created for this issue number: https://github.com/codice/ddf/pull/4537
