### ISSUE TITLE
Web apps embedded in the source action iframe do not work as expected

### ISSUE THREAD

**Issue by rymach** [codice/ddf#4355]
assign to @rymach 

### Description
See steps

### Steps to Reproduce
1. add a source action pointing to some webapp url 
2. click the source action on the sources page 
3. attempt to interact w/ the webapp in the iframe
4. errors appear in console, webapp doesn't work

#### Expected behavior :
webapp works 

#### Actual behavior:
webapp doesn't work, 
errors in console

#### Reproduces how often:
100%

#### Platform and environment:
N/A

### Affects versions
all

**Comment by bdeining** [comment]
@rymach can we post some screenshots and elaborate on `expected` vs `actual` behaviors?

**Comment by adimka** [comment]
We don't have updated guidelines for GitHub issue formats - but we should still try and adhere to the quality standards for tickets here: https://codice.atlassian.net/wiki/spaces/DDF/pages/37552149/JIRA+Primer+Best+Practices
