### ISSUE TITLE
Add a changelog to DDF

### ISSUE THREAD

**Issue by andrewkfiedler** [codice/ddf#4384]
### Description
Why is this change being proposed?
As a user (developer, integrator), I would like a changelog so I can see what changes have been made between each release or version.  

Who would want this change implemented?
Users, developers, integrators.  

Why should this be added to the codebase?
When it comes time to release, we'll have a good set of information to provide people with as to what is going to be changed if they upgrade to the latest.  This will help them make better decisions on when and how to go about upgrading.  

#### Expected behavior:
If we add a changelog, I would expect us to need to update the PR template to include updating the changelog.

I don't expect us to come up with a perfect format upfront, I expect we'll iterate on it over time based on what works well and what doesn't.  

### Version
2.14

### Additional Information
https://keepachangelog.com/en/1.0.0/ has additional information on why.
https://github.com/facebook/react/blob/master/CHANGELOG.md is a good example of a well maintained changelog.

# Example of what it could be follows

### Added
* Ability for users to set their home location for the maps ([@glenhein](https://github.com/glenhein) in [#4020](https://github.com/codice/ddf/pull/4020))

### Changed
* Login page will autofocus on username ([@andrewkfiedler](https://github.com/andrewkfiedler) in [#4376](https://github.com/codice/ddf/pull/4376))
* Filtering experience in dropdowns update ([@vinamartin](https://github.com/codice/ddf/commits?author=vinamartin) in [#4254](https://github.com/codice/ddf/commit/cc2340bf95bdc8fb30887b08a6c155ae5226b8f7))

### Deprecated
* ConfigurationFileProxy and EmbeddedSolrFiles ([@austinsteffes](https://github.com/austinsteffes) in [#3367](https://github.com/codice/ddf/pull/3367))

### Removed
* Standard Search UI and CometD ([@clockard](https://github.com/clockard) in [#3656](https://github.com/codice/ddf/pull/3656))

### Fixed 
* Rendering of large number of attributes on result forms ([@hayleynorton](https://github.com/hayleynorton) in [#4174](https://github.com/codice/ddf/pull/4174))

### Security
* Check that the user is logged in for every UI Websocket request ([@brjeter](https://github.com/brjeter) in [#4368](https://github.com/codice/ddf/commit/37b6f44ced47e7779cf771f9537189fda58dd13d))

**Comment by pklinef** [comment]
DDF used to have a CHANGES.md.  We had some challenges with it (e.g. knowing when something was noteworthy enough to be included to balance signal to noise) but that might have been due to the long release cycles.  I am for trying it again now that we are about to start monthly releases.

https://github.com/codice/ddf/blob/2.10.x/CHANGES.md
