### ISSUE TITLE
The DDF distribution doesn't start with an empty .m2 directory

### ISSUE THREAD

**Issue by Kjames5269** [codice/ddf#4385]
### Description
The unzipped DDF Distribution doesn't work with an empty M2
Workarounds involve having internet connectivity.
Severity: Major

### Steps to Reproduce

Unzip DDF
rename your ~/.m2 to ~/.m3
disconnect from the internet
start DDF

#### Expected behavior :

DDF starts successfully

#### Actual behavior:

DDF fails to start, trying to find the apache/aries/proxy/1.1.4 artifact 

#### Reproduces how often:

100%

#### Platform and environment:

All

### Affects versions

Master and release 2.13.x

**Comment by Bdthomson** [comment]
This was hitting me yesterday and I was 100% sure that I was rebased ontop of 836d171708178a9b06fcca5019ab3e626e436afd. Thought I was going crazy.

**Comment by oconnormi** [comment]
I just got the same issue this morning but due to `Could not find artifact io.fabric8.kubernetes:kubernetes-karaf:xml:features:3.1.12`

**Comment by Kjames5269** [comment]
@oconnormi I'm not sure if you've figured out the issue you were seeing but this issue _should_ be fixed
