### ISSUE TITLE
Add backend support for individual metacard to CSV transformation 

### ISSUE THREAD

**Issue by cantstoptheunk** [codice/ddf#4398]
### Description

As a user, I want the backend to support transforming to CSV so that I can import them to excel or another tool for further analysis.

#### Expected behavior:

The ability for the backend to transform a metacard into CSV format.

**Comment by coyotesqrl** [comment]
Should we provide functionality for exporting a group of results as any other format besides CSV? If so, I would suspect that would change the design from a single bundle to attach to, perhaps, a list of implementors of size N that could be attached at runtime.

What are the ramifications of the change, what are the downsides to it, and how should it be designed to be future-proof?

It would probably have been good to have at least a little conversation on this prior to jumping right into posting the PR.

**Comment by rzwiefel** [comment]
@coyotesqrl So this is purely for adding a transformer to allow exporting a single file as CSV, There is already another separate work being done to allow a selection of N many results and choosing any available transformer to export them as (https://github.com/codice/ddf/pull/4394).

This work is just adding a Csv metacard transformer and then registering it as another metacard transformer. We'll update the Issue description to align it with the intended goals. 

I think its a little more difficult to see the broader scope of work that's happening from a single ticket (without manually linking github issues or without creating a board to track the set of work). While some work (spread across a few issues) might be too small to be tracked using a github project (which feels decently heavy weight) we should probably discuss and agree on some standard to help correlate work across individual tickets - even if its just linking the other tickets.
