### ISSUE TITLE
Implement Faceting Powered Dropdown in Advanced Query Form

### ISSUE THREAD

**Issue by willwill96** [codice/ddf#4408]
### Description
Description of the issue
With faceted queries, we can provide users with suggestions for their queries.
Ex. if the selected attribute was car make the suggestions might be Ford, Subaru, etc. 

Why is this change being proposed?
This improvement will provide a more user friendly experience when creating query forms, by providing options based on the ingested data.

#### Expected behavior:
When selecting attributes from the advanced query form, suggestions are populated in a dropdown

### Version

2.14.0

**Comment by emmberk** [comment]
https://github.com/codice/ddf/pull/4409 This new config/feature needs documentation. I'm reopening this issue so that this can be addressed.
