### ISSUE TITLE
Logout doesn't work for certain NameIdTime query parameter values

### ISSUE THREAD

**Issue by bakejeyner** [codice/ddf#4462]
### Description

The logout endpoint takes in a `NameIdTime` query parameter. When this query parameter is extracted from the url it is URL Decoded. The problem is that it was never URL Encoded, so the crypter was erroring out when trying to decrypt the value.

### Steps to Reproduce

1. Log into the system
2. Log out of the system; about a 50% reproduction rate

#### Expected behavior :
Logged out.

#### Actual behavior:
50% of the time an error is shown and the user is not logged out.

#### Reproduces how often:
50%

**Comment by bakejeyner** [comment]
Working on it.

**Comment by vinamartin** [comment]
Fix was merged.
