### ISSUE TITLE
Drop issue numbers from Pull Request titles

### ISSUE THREAD

**Issue by andrewkfiedler** [codice/ddf#4501]
# Description of the issue
At the moment I find it a bit hard to scan the Pull Requests (PRs) and find what I'm looking for.  Each one is prefaced with a random number that doesn't help me in determining whether or not I want to look at the PR.  

I'm proposing we drop the prefixes from the PR titles.

# Why is this change being proposed?
I think in the past we used this system in order to differentiate between PRs to master vs PRs to another branch, but that can now be handled through the label system.  It can also be handled by filtering with `base` set.

Similarly, it was also used to denote a WIP.  However github now has official (or coming soon) support for WIP.  We also, once again, now have labels.

Look at other repositories and how they do PRs: https://github.com/AnalyticalGraphicsInc/cesium/pulls, https://github.com/facebook/react/pulls

I don't know all the history, so maybe I'm missing another reason to keep it as is.  But I think moving to drop the prefix will reduce a lot of the noise on the page when trying to scan through PRs.

**Comment by pklinef** [comment]
The biggest factor was to link back to Jira and to be able to do so quickly from git one line history views.  I think this will no longer be an issue if we fully adopt Github issues.

**Comment by vinamartin** [comment]
+1

**Comment by shaundmorris** [comment]
By label system do we still have an issue where everybody cannot currently set a label?

**Comment by vinamartin** [comment]
If we want to move forward with this, I think the best action is to announce it in the Google group and by helping contributors by modifying their PR titles as we move forward.
Is this something you're planning on doing Andrew?

**Comment by andrewkfiedler** [comment]
We did it!  Sort of, it's kind of the wild west now.
