### ISSUE TITLE
Warning missing for Lat/Lon being out of allowed parameters

### ISSUE THREAD

**Issue by BernardIgiri** [codice/ddf#4512]
Verify that the user receives a notification when an entered latitude in decimal degrees falls outside 90 degrees to -90 degrees or a entered longitude in decimal degrees falls outside 180 degrees and -180 degrees.

No warning message appears the UI simply does not allow the user to enter the value over the configured parameters

**Comment by vinamartin** [comment]
I believe this might be fixed in https://github.com/codice/ddf/pull/4229. 
Can you confirm @BernardIgiri so we can close this issue?
