### ISSUE TITLE
Groups not interpreted from users.properties file

### ISSUE THREAD

**Issue by singhdan** [codice/ddf#4519]
### Description
If a users.properties file contains any groups definitions then the roles are not parsed correctly. The \_g\_: value comes back as a role rather than it being expanded to editor and writer.

### Steps to Reproduce
1. Edit the users.properties file to contain a group definition and assign that group to a user
e.g. 
admin=admin,group,admin,manager,viewer,system-admin,systembundles,\_g\_:mygroup
localhost=localhost,group,admin,manager,viewer,system-admin,system-history,systembundles
\_g\_\:mygroup = group,editor,writer
2. Start DDF
3. Using karaf set the log level to TRACE (log:set TRACE ddf.security.pdp)
4. Log into DDF as admin
5. View the log file and observe that _g_:mygroup is not expanded as a role and appears in the xacml request

#### Expected behavior :
The \_g\_:mygroup should have been expanded to editor and writer 

#### Actual behavior:
Admin is given the role of '_g_:mygroup'

#### Reproduces how often:
100%

#### Platform and environment:
Windows Server 2012 R2, Chrome, JDK 1.8.0_144

### Affects versions
2.14

**Comment by coyotesqrl** [comment]
@blen-desta & @bakejeyner this looks like an issue you might want to track.

@singhdan Are you planning on putting up a PR for this or are you hoping someone will pick it up and work on it?

**Comment by singhdan** [comment]
I'm going to submit a PR for it. I've got it ready, was just waiting for the reviewers
