### ISSUE TITLE
Exporting All Results from Table View Fails To Display Admin Configurable Message 

### ISSUE THREAD

**Issue by Schachte** [codice/ddf#4524]
### Description

Currently, when trying to export all results from the table view on Intrigue, a message will warn the user if the user-entered value exceeds the admin configurable value. 

However, when choosing the `Export All` results option, it doesn't warn the user that _only_ the admin configurable amount will be exported and not all of them. This is confusing from a UX perspective. Rework prototype pictured below.

<img width="1341" alt="Screen Shot 2019-03-11 at 12 26 56 PM" src="https://user-images.githubusercontent.com/7055226/54154487-39fb4200-43ff-11e9-9b29-74f1764f5b90.png">
<img width="560" alt="Screen Shot 2019-03-11 at 12 26 51 PM" src="https://user-images.githubusercontent.com/7055226/54154489-39fb4200-43ff-11e9-9a62-64b2162b77ee.png">

This will also refactor the placeholder to request entering a numerical field, whereas now it asks for the user to enter a `city or region` when this is an integer input field only. 

## Testing Export Message

1. Ingest data into DDF
2. Open table view
3. Select the `Export` button
4. When choosing `All` from the dropdown, it should display a message if it exceeds the admin configurable limit (see note below to modify the limit)

```
To modify the admin configurable limit to a lower number to make it easier to test this, open up the catalog-ui-search settings from the admin page. Set this number to something small like 5, then retest
```

## Testing Placeholder

1. When following the above steps for exporting, swap the dropdown to `custom number`
2. When the number is removed, there should be a placeholder that is present.
3. Previously, the placeholder said `Enter a city or region` but now it should say something along the lines of `Enter number of results you would like to export`

**Comment by vinamartin** [comment]
Issue merged.
