### ISSUE TITLE
Update query endpoints to support standalone queries

### ISSUE THREAD

**Issue by bellcc** [codice/ddf#4569]
### Description

The current version of DDF does not support queries that exist outside of a workspace. We will be adding in the necessary backend support to make queries standalone. This will enable more complex features involving queries. Additionally we will update any existing query endpoints to use new technologies and perform any quality of life updates that enable us to work with queries more easily. 

#### Expected behavior:
Queries can be created outside the context of a workspace. 
Queries can be created, retrieved, updated, and deleted on a per user basis. 

### Version
2.15.0

### Additional Information
None

**Comment by ethantmanns** [comment]
This is referring to some sort of persistent search queries, right? Maybe we should mention that, because I think it's not accurate to say that DDF doesn't support _any_ queries outside of workspaces
