### ISSUE TITLE
Fix stopkey error message on windows

### ISSUE THREAD

**Issue by nsuvarna** [codice/ddf#4584]
### Description

When starting up ddf on windows, the following errors show up: `The system cannot find the file specified.` and `Could Not Find C:\Users\<user>\projects\ddf\distribution\ddf\target\ddf-2.15.0-SNAPSHOT\bin\STOPKEY`

DDF still works normally, so these messages are misleading.

@ahoffer 

#### Expected behavior:
The misleading messages are removed or fixed

### Version
2.15.0

**Comment by ahoffer** [comment]
Let's look at either invoking the file delete command silently or directing the output from the command to NUL
