### ISSUE TITLE
The WFS 1.1.0 filter delegate should support temporal queries

### ISSUE THREAD

**Issue by jrnorth** [codice/ddf#4644]
### Description
The WFS 1.1.0 filter delegate does not implement `before`, `after`, `during`, or `relative` so any temporal query passed to it results in an `UnsupportedOperationException` which causes it to fail immediately.

#### Expected behavior:
`before`, `after`, `during`, and `relative` temporal queries can be sent successfully to a WFS 1.1.0 source. They should be mapped to `PropertyIsLessThan`, `PropertyIsGreaterThan`, `PropertyIsBetween`, and `PropertyIsBetween`, respectively.

### Version
2.15.0

**Comment by jlcsmith** [comment]
@jrnorth - Can you confirm that the WFS 1.1.0 specification supports temporal operators?  It looks like it uses the [filter encoding spec 1.1.0](http://schemas.opengis.net/filter/1.1.0/filter.xsd) and I don't see temporal operators in there.

**Comment by jrnorth** [comment]
@jlcsmith Maybe I need to reword the issue. `after`, `before`, `during`, and `relative` are all translated into `PropertyIsGreaterThan/PropertyIsLessThan/PropertyIsBetween` in the outgoing query to the WFS source. If you're using Intrigue's query builder then the `after`/`before`/`during`/`relative` methods will be called on the filter delegate and the WFS 1.1.0 filter delegate currently does not implement them.

**Comment by jlcsmith** [comment]
@jrnorth that makes sense then.  It will be up to the WFS service on whether it correctly handles dates with those filters.
