### ISSUE TITLE
Geos from default search forms are rendered on the map even after a different form is used to search

### ISSUE THREAD

**Issue by mojogitoverhere** [codice/ddf#4680]
### Description

This only occurs if the user has a default search form configured that contains an `anyGeo` filter.

When user creates a new search, the default search form is shown and the geos are correctly rendered on the map. When the user changes to another search from the default, the geos are temporarily removed from the map, but then reappear when the user runs the search with the new form.
### Steps to Reproduce

1. Create a new search form A with an `anyGeo` filter
2. Set search form A as your default
3. Create another search form B
4. Refresh the page
5. Create a new search (the default form A appears)
6. Switch to search form B using the "User Another Search Form" action
7. See that the `anyGeo` from search form A disappears
8. Click "Search"
9. See that the 'anyGeo` from search form A reappears

#### Expected behavior :

the geo from search form A *is not* rendered on the map

#### Actual behavior:

the geo from search form A *is* rendered on the map

**Comment by vinamartin** [comment]
Fix merged
