### ISSUE TITLE
Documentation module build can allow content to be duplicated

### ISSUE THREAD

**Issue by ricklarsen** [codice/ddf#4703]
### Description
Because of the way the content directories are copied into a common directory, sections can be duplicated if a maven `clean` step is omitted between switching versions or during a release build. Adding a version number to the directories would cause only the correct files to be used each time.

### Steps to Reproduce

1. check out a release branch
2. build with `mvn install`
3. check out master branch
4. build with `mvn install`
(build will likely fail unit tests if branches have diverged, but html files can be opened and checked)

**Comment by emmberk** [comment]
Alliance ticket: [CAL-516](https://codice.atlassian.net/browse/CAL-516)
