### ISSUE TITLE
DDF sends urls that are too long to Solr when deleting from CSW

### ISSUE THREAD

**Issue by Corey-Collins** [codice/ddf#4734]
#### Expected behavior :

Sending a csw delete transaction removes records permanently from Solr
#### Actual behavior:

A csw deletion transaction with many records (e.g. 1000) returns 400 bad request. This is being caused by DDF sending too many ids in a url to Solr.

#### Reproduces how often:

100%

### Affects versions

DDF 2.15.0

### Additional Information

The exception is being thrown at
https://github.com/codice/ddf/blob/4edd5c9cc1d5d266866afb48e9b130b7beb8bec1/catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java#L343
and will easily be fixed by turning down the `GET_BY_ID_LIMIT` constant.

**Comment by jrnorth** [comment]
I'm unable to reproduce this. I ingested the reuters dataset (21,578 records) and deleted using the following CSW delete request to delete everything:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<csw:Transaction service="CSW" version="2.0.2"
    xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:ogc="http://www.opengis.net/ogc">
    <csw:Delete typeName="csw:Record" handle="something">
        <csw:Constraint version="2.0.0">
            <ogc:Filter>
                <ogc:PropertyIsLike wildCard="%" singleChar="_" escapeChar="\">
                   <ogc:PropertyName>id</ogc:PropertyName>
                   <ogc:Literal>%</ogc:Literal>
                </ogc:PropertyIsLike>
            </ogc:Filter>
        </csw:Constraint>
    </csw:Delete>
</csw:Transaction>
```

The deletion was successful.

**Comment by Corey-Collins** [comment]
@jrnorth i will have @willwill96 who is heroing this check if he also has no problem with this. there is a good chance this is just independent on my environment

**Comment by Corey-Collins** [comment]
im still receiving the csw response:
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ows:ExceptionReport xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ns4="http://www.w3.org/1999/xlink" xmlns:ns5="http://www.w3.org/2001/SMIL20/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ows="http://www.opengis.net/ows" xmlns:dct="http://purl.org/dc/terms/" xmlns:ns9="http://www.w3.org/2001/SMIL20/Language" xmlns:ns10="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" ns10:schemaLocation="http://www.opengis.net/csw /ogc/csw/2.0.2/CSW-publication.xsd">
    <ows:Exception exceptionCode="TransactionFailed" locator="something">
        <ows:ExceptionText>Unable to delete record(s).</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
