### ISSUE TITLE
Update quick start instructions for editing localhost references

### ISSUE THREAD

**Issue by ricklarsen** [codice/ddf#4782]
### Description

The instructions for a remote headless server includes a step to update references to localhost. However, there are some exceptions that need to be noted to ensure proper configuration. 

In users.properties: `localhost-data-manager` should not be changed
in users.attributes: the `localhost.local` email addresses should either not be changed, or updated to a valid email address.

**Comment by emmberk** [comment]
I don't think modifying the emails in users.attributes will cause an issue, right?

**Comment by ricklarsen** [comment]
> I don't think modifying the emails in users.attributes will cause an issue, right?

it shouldn't

**Comment by emmberk** [comment]
> > I don't think modifying the emails in users.attributes will cause an issue, right?
> 
> it shouldn't

Ok. You can probably remove that part from the issue description.
