### ISSUE TITLE
After paging through results, editing a search starts the new search on the current page instead of page 1

### ISSUE THREAD

**Issue by Bdthomson** [codice/ddf#4794]
### Description
After paging through results, editing a search starts the new search on the current page

### Steps to Reproduce
1. Set page size to something low like 3.
2. Make a query and then go to page 4.
3. Edit your query and click save/search.

#### Expected behavior :
Search behaves as if I click the Play button, and starts me back at page 1.

#### Actual behavior:
Search re-runs but I'm still on page 4.

#### Reproduces how often:

100%

### Affects versions
2.15.0-SNAPSHOT

**Comment by jrnorth** [comment]
Is this issue different from https://github.com/codice/ddf/issues/4765?

**Comment by Bdthomson** [comment]
Yes, closing
