### ISSUE TITLE
Unable to manually enter or edit USNG / MGRS for Point-Radius search

### ISSUE THREAD

**Issue by derekwilhelm** [codice/ddf#4875]
### Description
When entering a geo search and selecting the Point-Radius option, the validation on the USNG / MGRS entry field prevents a user from typing in a manual value.  You can copy/paste a value into that field but you cannot type one in manually.

### Steps to Reproduce
1. Open `Advanced Search` and select `anyGeo`
2. Select `Point-Radius` in the drop down menu after Intersects
3. Select `USNG / MGRS`
4. Attempt to type in a value such as `14R PU`
5. Notice that no value is able to be typed one character at a time.
6. Copy/Paste `14R PU` into the field, which it allows
7. Attempt to modify the value to `13R PU`
8. If the 4 is deleted, the field will be blanked.  If the 3 is added before or after the 4, the field will be blanked.  The only way to get it to work is to copy a 3, select the 4 and paste over it.

#### Expected behavior :
A user should be able to manually enter and/or edit a USNG / MGRS value for Point-Radius

#### Actual behavior:
The field doesn't allow them to type at all or will blank out the field during editing.

#### Reproduces how often:
All the time for Point-Radius.  The USNG / MGRS field for Bounding Box does not have this problem.

### Affects versions
2.14.0
2.15.0

**Comment by andrewkfiedler** [comment]
This appears to work in the latest version.
