### ISSUE TITLE
Changing Intrigue Number of Search Results setting causes result pagination to act unexpectedly

### ISSUE THREAD

**Issue by johnsliao** [codice/ddf#4895]
### Description

Changing Intrigue Number of Search Results setting causes result pagination to act unexpectedly. By default, the number of search results is set to 250. 

Decreasing it to a number less than the number of results returned. I tried a search with `7` results returned and `Number of Search Results` set to `4`. Results were returned as such:

Page 1
- Result 1
- Result 2
- Result 3
- Result 4

Page 2
- Result 1
- Result 2
- Result 3
- Result 4

Page 3
- Result 5
- Result 6
- Result 7

Page 4
- Result 5
- Result 6
- Result 7

### Affects versions

2.15.0

### Additional Information

7 results but was able to get to Page 4
![image](https://user-images.githubusercontent.com/10492153/58638725-6e2a2480-82c3-11e9-9a4f-98e5345c0be4.png)

Search settings
![image](https://user-images.githubusercontent.com/10492153/58638805-987be200-82c3-11e9-9c51-48a1dc265915.png)

**Comment by andrewkfiedler** [comment]
For those looking into this in the future, it appears the issue might be tied to caching.  

Turning off `Enable Cache` in the Admin UI eliminated the issue.
