### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [codice/ddf#5057]
Hi
The following lines have cryptographic API misuses. <br> File name => libs/httpproxy/proxy-camel-route/src/main/java/org/apache/commons/httpclient/contrib/ssl/AuthSSLProtocolSocketFactory.java: Line number => 200: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java: Line number => 247: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java: Line number => 524: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java: Line number => 491: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java: Line number => 384: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java: Line number => 200: API name => Signature:<BR> File name => platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java: Line number => 202: API name => Signature:<BR> File name => platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java: Line number => 169: API name => Signature:<BR> File name => platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java: Line number => 280: API name => Signature:<BR> File name => platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java: Line number => 287: API name => Signature:<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 485: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 488: API name => KeyStore:<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 505: API name => KeyStore:<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 496: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 451: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to load<BR> File name => platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java: Line number => 449: API name => KeyStore:Operation on object of type java.security.KeyStore object not completed. Expected call to load<BR> File name => catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java: Line number => 70: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by vinamartin** [comment]
Bot issue. Closing.
