### ISSUE TITLE
Unable to add security.access-individuals to resource metacards

### ISSUE THREAD

**Issue by andrewkfiedler** [codice/ddf#5234]
### Description
Using the inspector to add security.access-individuals to resource metacards results in this error. 
<img width="630" alt="Screen Shot 2019-08-17 at 2 13 09 AM" src="https://user-images.githubusercontent.com/11984853/63288681-27204f80-c272-11e9-84f5-9d98c508ae2a.png">

Adding them to query metacards does not result in this error.

**Comment by Bdthomson** [comment]
Could not reproduce

**Comment by andrewkfiedler** [comment]
Should we reopen this @Bdthomson ?
