### ISSUE TITLE
OperationPlugin does not pass the correct action to the security checks.

### ISSUE THREAD

**Issue by beyelerb** [codice/ddf#5331]
### Description
The OperationPlugin hard-codes all actions to read. In order for fine-grained authorization, the underlying policy decision points need to know the actual action being performed. For XACML-based policy control to be effective for all catalog operations, this needs to be updated.

### Steps to Reproduce
1. Enable XACML policy processing
2. Enable DEBUG logging for XACMLClient
3. Observe that action is read for all catalog operations

#### Expected behavior :
The action should reflect the current catalog operation being performed - CRUD.

#### Actual behavior:
The action is always reported as READ

#### Reproduces how often:
100%

#### Platform and environment:
All

### Affects versions
2.16.x, 2.17.x

**Comment by vinamartin** [comment]
Pull request merged.
