### ISSUE TITLE
Advanced search's anyGeo keyword gazetteer does not work as expected

### ISSUE THREAD

**Issue by jordanwilking** [codice/ddf#5332]
### Description

major bug

anyGeo's "keyword" gazetteer looks like it's always in offline mode. Must ingest for it to work, despite the map gazetteer working in online mode.

### Steps to Reproduce

1. Go to advanced search
1. Select anyGeo filter
1. Choose "Keyword" from the list of geos
1. Attempt to type a location into the gazetteer. No result will ever be found and you will be unable to populate the search box on offclick.

#### Expected behavior :

Gazetteer should find locations, be filled on offclick, and searches should filter with selected option. I would expect the functionality to mirror the actual gazetteer's functionality.

#### Actual behavior:

Unable to select a location in the gazetteer.

<img src="https://user-images.githubusercontent.com/22667297/64883457-45306400-d614-11e9-8060-433785a49bc8.png" height=50% width=50% />

#### Reproduces how often:

100%

#### Platform and environment:

Windows, Mac, Chrome, everything else standard.

### Affects versions

Checked on 2.18.0 Snapshot

**Comment by jrnorth** [comment]
And this is with data loaded into the gazetteer?

**Comment by jordanwilking** [comment]
It wasn't. I expected it to work the same as the map gazetteer. When gazetteer is in online mode, I expected them both to pull from the online source.

**Comment by jordanwilking** [comment]
Might be intended as Keyword was used instead of Gazetteer 🤷‍♂
