### ISSUE TITLE
FilterBuilder produces invalid AFTER and BEFORE filters

### ISSUE THREAD

**Issue by peterhuffer** [codice/ddf#5469]
### Description
When creating a Filter with the FilterBuilder, and converting it to CQL, then back to Filter using gt-cql classes, the CQL that was generated initially is not valid.

### Steps to Reproduce
Run the following test

```
Filter filter = filterBuilder.attribute("someAttr").after().date(new Date());
String cql = ECQL.toCql(filter);
ECQL.toFilter(cql)
```
and an exception will be thrown that the cql could not be translated back to ECQL.

#### Expected behavior :
Filters created with the FilterBuilder can be converted to CQL and then back to a Filter.

#### Actual behavior:
The generated CQL throws an exception when trying to convert it back to Filter.

#### Reproduces how often:
100%

#### Platform and environment:
Windows, JDK8

### Affects versions
master, 2.16.2 and probably all versions before!

**Comment by Lambeaux** [comment]
On hold awaiting for a Geotools upgrade.
