### ISSUE TITLE
Migrate ddf-registry to a new repo

### ISSUE THREAD

**Issue by shaundmorris** [codice/ddf#5541]
# Description
DDF Registry rarely changes and could be separated out into its own repo along with its itests. This would save time overall of running all itests.

### Version
2.21

### Additional Information
Target repo is https://github.com/codice/ddf-registry

**Comment by vinamartin** [comment]
@shaundmorris I see the code has been migrated over, can we close this issue or is there remaining work to be done?

**Comment by shaundmorris** [comment]
@vinamartin sorry for the delayed response. I still need to put up the PR here to remove the ddf-registry from this repo.
