### ISSUE TITLE
Improve documentation about downloading resources

### ISSUE THREAD

**Issue by ricklarsen** [codice/ddf#5569]
### Description

Downloading resources is a very important part of DDF, and the documented details of the metadata attributes should be enhanced to provide more specific guidance.

**Comment by ahoffer** [comment]
Additional information from a Slack convo. I think giving guidance to developers about when to set these values and how to know if they have been set correctly is important.

> phil
> resource-uri is a URI that the local DDF based system knows how to retrieve but a client might not be able to.  For example, content:, file:, wfs:, etc.  Resource resolvers are used to get the bytes of these URI if a request for that resource is made to the catalog framework.
> 
> phil 
> resource-download-url is a URL usually of the local DDF system (REST endpoint) that will resolve and get the bytes for the resource.  This is the attribute clients should use.
> 
> phil 
> Similar pattern for resource.derived-* attributes but for files derived from the original resource like overlays.
> 
> rick
> So, is this the update we want to add to those descriptions?
> 
> phil
> Probably not as-is.  I just wanted to get some of the information out there to start a discussion.  Are those details clear enough?
> 
> phil  7 days ago
> Ideally it would focus on an external system view.  I included some internal details that would be important to developers of DDF but not to external integrators.

@pklinef
