### ISSUE TITLE
Add custom text notation options for 3D map

### ISSUE THREAD

**Issue by mdang8** [codice/ddf#5572]
### Description

Users should be able to view a specified metacard field next to pins on the 3D map in Intrigue.

#### Expected behavior:

When the custom text notation option is enabled in the admin console, a selected metacard attribute is displayed next to each metacard map marker. It should look similar to how map marker labels are displayed in Google Maps.

**Comment by andrewkfiedler** [comment]
Might be useful to talk a bit about this, we've already tackled similar work in a downstream project.
