### ISSUE TITLE
Improperly formatted Polygon or Line geo filters still allow execution of query 

### ISSUE THREAD

**Issue by hayleynorton** [codice/ddf#5593]
### Description
Line or Poylgon geo strings must be in the format `[[x,y],[x,y],[x,y],[x,y], ... ]`. If a user chooses to manually manipulate the string, for example by copy and pasting a location instead of using the drawing feature, a red bar reading "Not an acceptable value" appears, but the user could still execute the query.

### Steps to Reproduce
1. Start an anyGeo search with a line or polygon
2. Paste a WKT string into the geo string field (or any string not in the correct format; could also leave blank)
3. Click `Search` twice

#### Expected behavior :
The search should not be executed

#### Actual behavior:
The search is executed

#### Reproduces how often:
100%

**Comment by shaundmorris** [comment]
Closing since this was already merged on a couple of branches. On master here: https://github.com/codice/ddf/pull/5658
