### ISSUE TITLE
Result Form actions (vertical ellipsis) renders empty box when no actions are present

### ISSUE THREAD

**Issue by andrewzimmer** [codice/ddf#5815]
### Description
Result Form actions (vertical ellipsis) renders empty box when no actions are present

### Steps to Reproduce
This is happens for system forms or read-only forms

#### Expected behavior :
no vertical ellipsis on form item

### Additional Information
<img width="1026" alt="Screen Shot 2020-02-05 at 10 44 44 AM" src="https://user-images.githubusercontent.com/39923178/73877131-5b35ff80-4815-11ea-9f0b-44f19391d740.png">

**Comment by rzwiefel** [comment]
Did you mean to open this issue on GitHub.com/codice/ddf-ui ?

**Comment by andrewzimmer** [comment]
@rzwiefel I need to put up a pr in both repos, so not really sure what I should be doing for issues
