### ISSUE TITLE
[Negatively summarize the cause and effect of the bug]

### ISSUE THREAD

**Issue by amunizp** [codice/ddf#6337]
### Description
Failed to install on ubuntu 18.04
I was unable to install. 
Probably user error. 

### Steps to Reproduce
~/ddf-2.25.2$ mvn clean install
#### Expected behavior :
Feedback on packages missing, needing sudo, or a full install. 
#### Actual behavior:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.080 s
[INFO] Finished at: 2020-09-21T17:48:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/andres/Documents/scripts/ddf-2.25.2). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

#### Reproduces how often:
Every time. 
#### Platform and environment:
ubuntu 18.04
### Affects versions
ddf-2.25.2
### Additional Information
I also tried to post in the user google group but it does not let me post there.

**Comment by rzwiefel** [comment]
Hi @amunizp , apologies for not seeing this sooner. It looks like based of your folder name (ddf-2.25.2) you have a pre built ddf distribution (as opposed to the source code). For starting up a distribution you can use the `ddf` start script located in the `bin/` directory. You can read more in depth about it here in the documentation regarding installing ddf 
http://codice.org/ddf/docs/documentation.html#_quick_install_of_ddf


If you're looking to build the source code yourself you will want to clone the git repo (usually `git clone git@github.com:codice/ddf.git`) and then do a `mvn clean install`. The error above was actually saying how maven was ran but it could not find the `pom.xml` file (which is located in the git repo source code, but not the already built distribution). 

Hope this helps!

**Comment by rzwiefel** [comment]
I'll close this for now
