### ISSUE TITLE
Installing multiple Guava versions causes uses constraint violations

### ISSUE THREAD

**Issue by SmithJosh** [codice/ddf#6365]
### Description

Installing multiple versions of Guava results in uses constraint violations. The violations aren't fatal, but Karaf takes significantly longer to resolve bundle wiring. When testing installs took ~5x longer, long enough to cause timeouts during itests.

This is an issue because DDF contains features which _do_ install other versions of Guava.

This was originally discovered here (may provide additional context): https://github.com/codice/ddf/pull/6361#discussion_r499755225

### Steps to Reproduce

To reproduce:
1. Start DDF
2. Turn up the log level to view the non-fatal uses constraint violations:
```
log:set DEBUG
```
3. Run `feature:install camel-protobuf` (will install Guava)
4. Run `profile:install standard`

#### Expected behavior :

There are no uses constraint violations and the standard profile installs quickly

#### Actual behavior:

There are hundreds of uses constraint violations reported in the logs, and the install takes significantly longer than without the second Guava version installed.

Sample uses constraint violation:
```
2020-10-05T08:56:24,035 | DEBUG | tures-3-thread-1 | ResolverImpl                     | ternal.resolver.Slf4jResolverLog   45 | 17 - org.apache.karaf.features.core - 4.2.9 | Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource solr-factory-impl [solr-factory-impl/2.26.0] because it is exposed to package 'com.google.common.collect' from resources com.google.guava [com.google.guava/25.1.0.jre] and com.google.guava [com.google.guava/25.1.0.jre] via two dependency chains.

Chain 1:
  solr-factory-impl [solr-factory-impl/2.26.0]
    import: (&(osgi.wiring.package=com.google.common.collect)(version>=25.1.0)(!(version>=26.0.0)))
     |
    export: osgi.wiring.package: com.google.common.collect
  com.google.guava [com.google.guava/25.1.0.jre]

Chain 2:
  solr-factory-impl [solr-factory-impl/2.26.0]
    import: (&(osgi.wiring.package=org.codice.ddf.platform.util)(version>=2.26.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=org.codice.ddf.platform.util; uses:=com.google.common.io
  platform-util [platform-util/2.26.0]
    import: (&(osgi.wiring.package=com.google.common.io)(version>=25.1.0)(!(version>=26.0.0)))
     |
    export: osgi.wiring.package: com.google.common.io; uses:=com.google.common.collect
    export: osgi.wiring.package=com.google.common.collect
  com.google.guava [com.google.guava/25.1.0.jre])
```

#### Reproduces how often:

100%

### Affects versions
2.26.x, master

**Comment by Lambeaux** [comment]
Commenting to keep the issue open.

**Comment by SmithJosh** [comment]
This is still an issue

**Comment by SmithJosh** [comment]
Still an issue
